name: "deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - "**.json"
      - "**.sh"
      - "**.yml"

concurrency:
  group: deploy-workflow
  cancel-in-progress: true

jobs:
  deploy-to-scf:
    name: Deploy to Tencent Cloud Serverless Cloud Function
    runs-on: ubuntu-latest
    steps:
      - name: Clone local repository
        uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install python dependencies
        run: pip install tencentcloud-sdk-python json5
      - name: Deploy
        run: |
          bash ./serverless/deploy.sh
          if [ $? -ne 0 ]; then
            exit 1;
          fi
        env:
          STAGE: dev
          SERVERLESS_PLATFORM_VENDOR: tencent
          TENCENT_SECRET_ID: ${{AKIDEsLaZIm12oKaZHjupUu51h7HFyShgQvA}}
          TENCENT_SECRET_KEY: ${{0lHXYKr891f2A3h5D5i6E6k8G8k7F7j4}}
          CRON: ${{ 0 30 0,16 * * * * }}
          REGION: ${{ secrets.REGION }}
          FUNCTION_NAME: ${{ secrets.FUNCTION_NAME }}

          DEFAULT_SONG_NUMER_CRON: "10 0 0 * * * *"
          DEFAULT_CRON: "0 30 0 * * * *"
          DEFAULT_REGION: "ap-guangzhou"
          DEFAULT_FUNCTION_NAME: "NeteaseCloudMusicTasks"
